name: Check for new note

on:
  push:
    branches:
      - master

  workflow_dispatch:

  schedule:
    - cron: '0 7-18 * * *'

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Ensure Gradle is executable
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run main.kt
        run: export PRONOTE_USER="${{ secrets.PRONOTE_USER }}" && export PRONOTE_PASS="${{ secrets.PRONOTE_PASS }}" && export NOTIF_CODE="${{ secrets.NOTIF_CODE }}" && ./gradlew run

      - name: Upload new notes
        uses: EndBug/add-and-commit@v9
